ARG BASE_IMAGE
FROM ${BASE_IMAGE}

RUN python -m pip install --no-cache-dir \
      http://blobstore.s3.ord1.coreweave.com/drivers/tensorflow/cuda11.8-ubuntu20.04-compute_90/tensorflow-2.12.0-cp38-cp38-linux_x86_64.whl
