ARG BASE_IMAGE="ghcr.io/coreweave/ml-containers/torch-extras:45d2f2f-nccl-cuda12.8.1-ubuntu22.04-nccl2.26.5-1-torch2.7.0-vision0.22.0-audio2.7.0-abi1"
ARG BUILDER_IMAGE="${BASE_IMAGE}"

# https://github.com/NVIDIA/JAX-Toolbox/blob/main/.github/container/Dockerfile.axlearn
# https://github.com/NVIDIA/JAX-Toolbox/blob/main/.github/container/Dockerfile.base

