image:
  # Ubuntu 22.04
  - cuda: 12.2.2
    os: ubuntu22.04
    nccl: 2.19.3-1
    nccl-tests-hash: 868dc3d
  - cuda: 12.1.1
    os: ubuntu22.04
    nccl: 2.18.3-1
    nccl-tests-hash: 868dc3d
  - cuda: 12.0.1
    os: ubuntu22.04
    nccl: 2.18.5-1
    nccl-tests-hash: 868dc3d
  # Ubuntu 20.04
  - cuda: 12.2.2
    os: ubuntu20.04
    nccl: 2.21.5-1
    nccl-tests-hash: 027b52a
  - cuda: 12.1.1
    os: ubuntu20.04
    nccl: 2.18.3-1
    nccl-tests-hash: 868dc3d
  - cuda: 12.0.1
    os: ubuntu20.04
    nccl: 2.19.3-1
    nccl-tests-hash: 868dc3d
  - cuda: 11.8.0
    os: ubuntu20.04
    nccl: 2.16.5-1
    nccl-tests-hash: 868dc3d
include:
  - torch: 2.3.0
    vision: 0.18.0
    audio: 2.3.0
