image:
  # Ubuntu 22.04
  - cuda: 12.2.2
    os: ubuntu22.04
    nccl: 2.19.3-1
    nccl-tests-hash: a72ab6c
  - cuda: 12.1.1
    os: ubuntu22.04
    nccl: 2.18.3-1
    nccl-tests-hash: a72ab6c
  - cuda: 12.0.1
    os: ubuntu22.04
    nccl: 2.18.5-1
    nccl-tests-hash: a72ab6c
  # Ubuntu 20.04
  - cuda: 12.2.2
    os: ubuntu20.04
    nccl: 2.19.3-1
    nccl-tests-hash: fb613ea
  - cuda: 12.1.1
    os: ubuntu20.04
    nccl: 2.18.3-1
    nccl-tests-hash: fb613ea
  - cuda: 12.0.1
    os: ubuntu20.04
    nccl: 2.19.3-1
    nccl-tests-hash: fb613ea
  - cuda: 11.8.0
    os: ubuntu20.04
    nccl: 2.16.5-1
    nccl-tests-hash: fb613ea
include:
  - torch: 2.2.0
    vision: 0.17.0
    audio: 2.2.0
