image:
  # Ubuntu 22.04
  - cuda: 12.6.2
    os: ubuntu22.04
  - cuda: 12.4.1
    os: ubuntu22.04
  - cuda: 12.2.2
    os: ubuntu22.04
  # Ubuntu 20.04
  - cuda: 12.6.2
    os: ubuntu20.04
  - cuda: 12.4.1
    os: ubuntu20.04
  - cuda: 12.2.2
    os: ubuntu20.04
include:
  - torch: 2.5.1
    vision: 0.20.0
    audio: 2.5.0
    image:
      nccl: 2.23.4-1
      nccl-tests-hash: c58f522
