cuda: [ 12.2.2, 12.1.1, 12.0.1, 11.8.0 ]
os: [ ubuntu22.04, ubuntu20.04 ]
exclude:
  # Not a supported combination
  - cuda: 11.8.0
    os: ubuntu22.04
include:
  - torch: 2.2.0
    vision: 0.17.0
    audio: 2.2.0
