image:
  - cuda: 12.2.2
    nccl: 2.19.3-1
    nccl-tests-hash: a72ab6c
  - cuda: 12.1.1
    nccl: 2.18.3-1
    nccl-tests-hash: a72ab6c
  - cuda: 12.0.1
    nccl: 2.18.5-1
    nccl-tests-hash: a72ab6c
include:
  - torch: 2.2.0
    vision: 0.17.0
    audio: 2.2.0
