vllm-commit:
  - '8260948cdc379d13bf4b80d3172a03d21a983e05'
flashinfer-commit:
  - 'v0.2.8'
builder-base-image:
  - 'ghcr.io/coreweave/ml-containers/nightly-torch-extras:8552fbc-nccl-25080505-cuda12.9.1-ubuntu22.04-nccl2.27.6-1-torch2.9.0a0-vision0.24.0a0-audio2.8.0a0'
final-base-image:
  - 'ghcr.io/coreweave/ml-containers/nightly-torch-extras:8552fbc-nccl-25080505-cuda12.9.1-ubuntu22.04-nccl2.27.6-1-torch2.9.0a0-vision0.24.0a0-audio2.8.0a0'
