vllm-commit:
  - 'v0.11.2'
flashinfer-commit:
  - 'v0.5.2'
builder-base-image:
  - 'ghcr.io/coreweave/ml-containers/torch:8a60b2d-nccl-cuda12.9.1-ubuntu22.04-nccl2.28.3-1-torch2.8.0-vision0.23.0-audio2.8.0-abi1'
final-base-image:
  - 'ghcr.io/coreweave/ml-containers/torch:8a60b2d-nccl-cuda12.9.1-ubuntu22.04-nccl2.28.3-1-torch2.8.0-vision0.23.0-audio2.8.0-abi1'
