vllm-commit:
  - 'v0.12.0'
flashinfer-commit:
  - 'v0.3.2'
builder-base-image:
  - 'ghcr.io/coreweave/ml-containers/torch:ssteel-vllm-0.12.0-e6b2d14-nccl-cuda12.9.1-ubuntu22.04-nccl2.28.3-1-torch2.9.0-vision0.24.0-audio2.9.0-abi1'
final-base-image:
  - 'ghcr.io/coreweave/ml-containers/torch:ssteel-vllm-0.12.0-e6b2d14-nccl-cuda12.9.1-ubuntu22.04-nccl2.28.3-1-torch2.9.0-vision0.24.0-audio2.9.0-abi1'
