vllm-commit:
  - 'v0.10.0'
flashinfer-commit:
  - 'v0.2.8'
builder-base-image:
  - 'ghcr.io/coreweave/ml-containers/torch-extras:es-torch-2.8.0-d0e58f6-nccl-cuda12.9.1-ubuntu22.04-nccl2.27.6-1-torch2.8.0-vision0.23.0-audio2.8.0-abi1'
final-base-image:
  - 'ghcr.io/coreweave/ml-containers/torch-extras:es-torch-2.8.0-d0e58f6-nccl-cuda12.9.1-ubuntu22.04-nccl2.27.6-1-torch2.8.0-vision0.23.0-audio2.8.0-abi1'
