vllm-commit:
  - 'v0.9.2'
flashinfer-commit:
  - 'v0.2.6.post1'
builder-base-image:
  - 'ghcr.io/coreweave/ml-containers/torch-extras:es-fa3-te-update-3f63255-nccl-cuda12.9.1-ubuntu22.04-nccl2.27.5-1-torch2.7.1-vision0.22.1-audio2.7.1-abi1'
final-base-image:
  - 'ghcr.io/coreweave/ml-containers/torch-extras:es-fa3-te-update-52eb826-base-cuda12.9.1-ubuntu22.04-torch2.7.1-vision0.22.1-audio2.7.1-abi1'
