vllm-commit:
  - 'v0.12.0'
flashinfer-commit:
  - 'v0.5.3'
builder-base-image:
  - 'ghcr.io/coreweave/ml-containers/torch:ssteel-vllm-0.12.0-ffd70f0-base-cuda12.9.1-ubuntu22.04-torch2.9.0-vision0.24.0-audio2.9.0-abi1'
final-base-image:
  - 'ghcr.io/coreweave/ml-containers/torch:ssteel-vllm-0.12.0-ffd70f0-base-cuda12.9.1-ubuntu22.04-torch2.9.0-vision0.24.0-audio2.9.0-abi1'
