name: build-test

# Canary build to validate that build.yml can build and push an image.

on:
  workflow_dispatch:
  push:
    paths:
      - "build-test/**"
      - ".github/workflows/build-test.yml"
      - ".github/workflows/build.yml"


jobs:
  build:
    uses: ./.github/workflows/build.yml
    secrets: inherit
    with:
      image-name: build-test
      folder: build-test
