on:
  workflow_dispatch:
  push:
    paths:
      - "gpt-neox-mpi/**"
      - ".github/workflows/gpt-neox-mpi.yml"
      - ".github/workflows/build.yml"


jobs:
  build:
    uses: ./.github/workflows/build.yml
    secrets: inherit
    with:
      image-name: gpt-neox-mpi
      folder: gpt-neox-mpi
      build-args: ""
