on:
  workflow_dispatch:
    inputs:
      base-image:
        description: 'Base image to use'
        required: true
      commit:
        description: 'Commit of Megatron to include'
        required: true
  push:
    paths:
      - "megatron/**"
      - ".github/workflows/megatron.yml"
      - ".github/workflows/build.yml"


jobs:
  build:
    uses: ./.github/workflows/build.yml
    secrets: inherit
    with:
      image-name: megatron
      folder: megatron
      build-args: |
        BASE_IMAGE=${{ inputs.base-image || 'ghcr.io/coreweave/ml-containers/torch-extras:es-actions-56f06ed-nccl-cuda12.6.2-ubuntu22.04-nccl2.23.4-1-torch2.5.1-vision0.20.0-audio2.5.0'}}
        COMMIT=${{ inputs.commit || 'main'}}
