on:
  workflow_dispatch:
    inputs:
      base-image:
        description: 'Base image to use'
        required: true
      commit:
        description: 'Commit of Megatron to include'
        required: true
  push:
    paths:
      - "megatron/**"
      - ".github/workflows/megatron.yml"


jobs:
  build:
    uses: ./.github/workflows/build.yml
    secrets: inherit
    with:
      image-name: megatron
      folder: megatron
      build-args: |
        BASE_IMAGE=${{ inputs.base-image || 'ghcr.io/coreweave/ml-containers/torch-extras:17ad6db-nccl-cuda12.9.1-ubuntu22.04-nccl2.29.2-1-torch2.10.0-vision0.25.0-audio2.10.0-abi1'}}
        COMMIT=${{ inputs.commit || 'main'}}
