on:
  workflow_dispatch:
    inputs:
      commit:
        description: 'Commit to build'
        required: true
        default: 'master'
  push:
    paths:
      - "sd-finetuner/**"
      - ".github/workflows/sd-finetuner.yml"
      - ".github/workflows/build.yml"


jobs:
  build:
    uses: ./.github/workflows/build.yml
    secrets: inherit
    with:
      image-name: sd-finetuner
      folder: sd-finetuner
      build-args: "--build-arg COMMIT=${{ github.event.inputs.commit }}"
      build-contexts: |
        kw=https://github.com/coreweave/kubernetes-cloud.git#${{ github.event.inputs.commit }}
