on:
  workflow_dispatch:
    inputs:
      commit:
        description: 'Commit to build'
        required: true
        default: 'master'
  push:
    paths:
      - "sd-inference/**"
      - ".github/workflows/sd-inference.yml"
      - ".github/workflows/build.yml"


jobs:
  build:
    uses: ./.github/workflows/build.yml
    secrets: inherit
    with:
      image-name: sd-inference
      folder: sd-inference
      build-args: |
        COMMIT=${{ github.event.inputs.commit }}
