on:
  push:
    paths:
      - "sglang/**"
      - ".github/workflows/sglang.yml"
      - ".github/configurations/sglang.yml"


jobs:
  get-config:
    name: Get sglang config
    uses: ./.github/workflows/read-configuration.yml
    with:
      path: ./.github/configurations/sglang.yml
  build:
    uses: ./.github/workflows/build.yml
    needs: get-config
    strategy:
      matrix: ${{ fromJSON(needs.get-config.outputs.config) }}
    secrets: inherit
    with:
      image-name: sglang
      folder: sglang
      platforms: linux/amd64,linux/arm64
      object-storage-secrets: true
      build-contexts: common=common
      tag-suffix: ${{ matrix.tag }}
      build-args: |
        BASE_IMAGE=${{ matrix.base-image }}
        SGLANG_COMMIT=${{ matrix.sglang-commit }}
        DECORD_COMMIT=${{ matrix.decord-commit }}
