on:
  workflow_dispatch:
  push:
    paths:
      - "slurm/**"
      - ".github/workflows/slurm.yml"
      - ".github/workflows/build.yml"

jobs:
  build:
    strategy:
      matrix:
        image:
        - name: "slurm-login"
          folder: slurm
          build-args: |
            BASE_IMAGE=registry.gitlab.com/coreweave/sunk/controller-extras:bc5a133d
        - name: "slurm-cw-cu117"
          folder: slurm
          build-args: |
            BASE_IMAGE=registry.gitlab.com/coreweave/sunk/slurmd-cw-cu117-extras:bc5a133d

    uses: ./.github/workflows/build.yml
    secrets: inherit
    with:
      image-name: ${{ matrix.image.name }}
      folder: ${{ matrix.image.folder }}
      build-args: ${{ matrix.image.build-args }}
