on:
  workflow_dispatch:
  push:
    paths:
      - "torch/**"
      - ".github/workflows/torch-nccl.yml"
      - ".github/workflows/torch.yml"
      - ".github/workflows/build.yml"


jobs:
  build:
    strategy:
      matrix:
        image:
          - cuda: 12.2.2
            nccl: 2.20.3-1
            nccl-tests-hash: 868dc3d
#          - cuda: 12.1.1
#            nccl: 2.18.3-1
#            nccl-tests-hash: 253a5b1
          - cuda: 12.0.1
            nccl: 2.19.3-1
            nccl-tests-hash: 868dc3d
#          - cuda: 11.8.0
#            nccl: 2.16.2-1
#            nccl-tests-hash: 253a5b1
        include:
          - torch: 2.0.1
            vision: 0.15.2
            audio: 2.0.2

    uses: ./.github/workflows/torch.yml
    secrets: inherit
    with:
      tag: ${{ format('nccl-cuda{0}-nccl{1}-torch{2}-vision{3}-audio{4}', matrix.image.cuda, matrix.image.nccl, matrix.torch, matrix.vision, matrix.audio) }}
      builder-base-image: ghcr.io/coreweave/nccl-tests:${{ matrix.image.cuda }}-cudnn8-devel-ubuntu20.04-nccl${{ matrix.image.nccl }}-${{ matrix.image.nccl-tests-hash }}
      base-image: ghcr.io/coreweave/nccl-tests:${{ matrix.image.cuda }}-cudnn8-devel-ubuntu20.04-nccl${{ matrix.image.nccl }}-${{ matrix.image.nccl-tests-hash }}
      torch-version: ${{ matrix.torch }}
      torchvision-version: ${{ matrix.vision }}
      torchaudio-version: ${{ matrix.audio }}
      build-extras: true
