name: torch-base

on:
  workflow_dispatch:
    inputs:
      image-name:
        required: false
        description: "Custom name under which to publish the resulting container"
        type: string
      image-tag-suffix:
        required: false
        description: "Custom tag suffix listing library versions under which to publish the resulting container"
        type: string
  push:
    paths:
      - "torch/**"
      - ".github/configurations/torch-base.yml"
      - ".github/workflows/torch-base.yml"
      - ".github/workflows/torch.yml"
      - ".github/workflows/build.yml"


jobs:
  get-config:
    name: Get torch:base Config
    uses: ./.github/workflows/read-configuration.yml
    with:
      path: ./.github/configurations/torch-base.yml
  build:
    name: Build torch:base
    needs: get-config
    strategy:
      matrix: ${{ fromJSON(needs.get-config.outputs.config) }}
    uses: ./.github/workflows/torch.yml
    secrets: inherit
    with:
      image-name: ${{ inputs.image-name }}
      tag: ${{ format('{0}-{1}', format('base-cuda{0}', matrix.cuda), inputs.image-tag-suffix || format('torch{0}-vision{1}-audio{2}', matrix.torch, matrix.vision, matrix.audio)) }}
      builder-base-image: nvidia/cuda:${{ matrix.cuda }}-devel-ubuntu20.04
      base-image: nvidia/cuda:${{ matrix.cuda }}-base-ubuntu20.04
      torch-version: ${{ matrix.torch }}
      torchvision-version: ${{ matrix.vision }}
      torchaudio-version: ${{ matrix.audio }}
      build-extras: true
