name: torch-nccl

on:
  workflow_call:
    inputs:
      torch-version:
        required: false
        type: string
      torchvision-version:
        required: false
        type: string
      torchaudio-version:
        required: false
        type: string
      triton-version:
        required: false
        type: string
      image-name:
        required: false
        type: string
      image-tag-suffix:
        required: false
        type: string
  workflow_dispatch:
    inputs:
      torch-version:
        required: false
        description: "Tagged version number from pytorch/pytorch to build"
        type: string
      torchvision-version:
        required: false
        description: "Tagged version number from pytorch/vision to build"
        type: string
      torchaudio-version:
        required: false
        description: "Tagged version number from pytorch/audio to build"
        type: string
      triton-version:
        required: false
        description: "Tagged version number from openai/triton to build"
        type: string
      image-name:
        required: false
        description: "Custom name under which to publish the resulting container"
        type: string
      image-tag-suffix:
        required: false
        description: "Custom tag suffix listing library versions under which to publish the resulting container"
        type: string
  push:
    paths:
      - "torch/**"
      - ".github/workflows/torch-nccl.yml"
      - ".github/workflows/torch.yml"
      - ".github/workflows/build.yml"


jobs:
  build:
    strategy:
      matrix:
        image:
          - cuda: 12.1.1
            nccl: 2.18.3-1
            nccl-tests-hash: 471f0db
          - cuda: 12.0.1
            nccl: 2.18.3-1
            nccl-tests-hash: 471f0db
          - cuda: 11.8.0
            nccl: 2.16.2-1
            nccl-tests-hash: 471f0db
        include:
          - torch:  ${{ inputs.torch-version       || '2.0.1'  }}
            vision: ${{ inputs.torchvision-version || '0.15.2' }}
            audio:  ${{ inputs.torchaudio-version  || '2.0.2'  }}
            triton: ${{ inputs.triton-version }}

    uses: ./.github/workflows/torch.yml
    with:
      image-name: ${{ inputs.image-name }}
      tag: ${{ format('{0}-{1}', format('nccl-cuda{0}-nccl{1}', matrix.image.cuda, matrix.image.nccl), inputs.image-tag-suffix || format('torch{0}-vision{1}-audio{2}', matrix.torch, matrix.vision, matrix.audio)) }}
      builder-base-image: ghcr.io/coreweave/nccl-tests:${{ matrix.image.cuda }}-cudnn8-devel-ubuntu20.04-nccl${{ matrix.image.nccl }}-${{ matrix.image.nccl-tests-hash }}
      base-image: ghcr.io/coreweave/nccl-tests:${{ matrix.image.cuda }}-cudnn8-devel-ubuntu20.04-nccl${{ matrix.image.nccl }}-${{ matrix.image.nccl-tests-hash }}
      torch-version: ${{ matrix.torch }}
      torchvision-version: ${{ matrix.vision }}
      torchaudio-version: ${{ matrix.audio }}
      triton-version: ${{ matrix.triton }}
      build-extras: true
