name: torch-nccl

on:
  workflow_call:
    inputs:
      image-name:
        required: false
        type: string
      image-tag-suffix:
        required: false
        type: string
  workflow_dispatch:
    inputs:
      image-name:
        required: false
        description: "Custom name under which to publish the resulting container"
        type: string
      image-tag-suffix:
        required: false
        description: "Custom tag suffix listing library versions under which to publish the resulting container"
        type: string
  push:
    paths:
      - "torch/**"
      - ".github/configurations/torch-nccl.yml"
      - ".github/workflows/torch-nccl.yml"
      - ".github/workflows/torch.yml"
      - ".github/workflows/build.yml"


jobs:
  get-config:
    name: Get torch:nccl Config
    uses: ./.github/workflows/read-configuration.yml
    with:
      path: ./.github/configurations/torch-nccl.yml
  build:
    name: Build torch:nccl
    needs: get-config
    strategy:
      matrix: ${{ fromJSON(needs.get-config.outputs.config) }}
    uses: ./.github/workflows/torch.yml
    secrets: inherit
    with:
      image-name: ${{ inputs.image-name }}
      tag: ${{ format('{0}-{1}', format('nccl-cuda{0}-nccl{1}', matrix.image.cuda, matrix.image.nccl), inputs.image-tag-suffix || format('torch{0}-vision{1}-audio{2}', matrix.torch, matrix.vision, matrix.audio)) }}
      builder-base-image: ghcr.io/coreweave/nccl-tests:${{ matrix.image.cuda }}-cudnn8-devel-ubuntu22.04-nccl${{ matrix.image.nccl }}-${{ matrix.image.nccl-tests-hash }}
      base-image: ghcr.io/coreweave/nccl-tests:${{ matrix.image.cuda }}-cudnn8-devel-ubuntu22.04-nccl${{ matrix.image.nccl }}-${{ matrix.image.nccl-tests-hash }}
      torch-version: ${{ matrix.torch }}
      torchvision-version: ${{ matrix.vision }}
      torchaudio-version: ${{ matrix.audio }}
      build-extras: true
