on:
  workflow_dispatch:
    inputs:
      commit:
        description: 'Commit to build'
        required: true
  push:
    paths:
      - "vllm-tensorizer/**"
      - ".github/workflows/vllm-tensorizer.yml"
      - ".github/workflows/build.yml"


jobs:
  build:
    uses: ./.github/workflows/build.yml
    secrets: inherit
    with:
      image-name: vllm-tensorizer
      folder: vllm-tensorizer
      tag-suffix: ${{ inputs.commit || 'b6553be1bc75f046b00046a4ad7576364d03c835'}}
      build-args: |
        COMMIT_HASH=${{ inputs.commit || 'b6553be1bc75f046b00046a4ad7576364d03c835'}}
        TRITON_COMMIT=96316ce5