on:
  workflow_dispatch:
    inputs:
      commit:
        description: 'Commit to build'
        required: true
  push:
    paths:
      - "vllm-tensorizer/**"
      - ".github/workflows/vllm-tensorizer.yml"
      - ".github/workflows/build.yml"


jobs:
  build:
    uses: ./.github/workflows/build.yml
    secrets: inherit
    with:
      image-name: vllm-tensorizer
      folder: vllm-tensorizer
      tag-suffix: ${{ inputs.commit || '51602eefd38250325e541abd28f051ffd7676c3f'}}
      build-args: |
        COMMIT_HASH=${{ inputs.commit || '51602eefd38250325e541abd28f051ffd7676c3f'}}