on:
  workflow_dispatch:
    inputs:
      commit:
        description: 'Commit to build'
        required: true
      vllm-flash-attn-version:
        description: 'vllm-flash-attn version to build'
        required: true
  push:
    paths:
      - "vllm-tensorizer/**"
      - ".github/workflows/vllm-tensorizer.yml"
      - ".github/workflows/build.yml"


jobs:
  build:
    uses: ./.github/workflows/build.yml
    secrets: inherit
    with:
      image-name: vllm-tensorizer
      folder: vllm-tensorizer
      tag-suffix: ${{ inputs.commit || '0408efc6d0c17fba17b2be38d0d0f02e96d2bf9d'}}
      build-args: |
        COMMIT_HASH=${{ inputs.commit || '0408efc6d0c17fba17b2be38d0d0f02e96d2bf9d'}}
        VLLM_FLASH_ATTN_VERSION=${{ inputs.vllm-flash-attn-version || '720c94869cf2e0ff5a706e9c7f1dce0939686ade'}}