on:
  push:
    paths:
      - "vllm-tensorizer/**"
      - ".github/workflows/vllm-tensorizer.yml"
      - ".github/workflows/build.yml"


jobs:
  get-config:
    name: Get vllm-tensorizer config
    uses: ./.github/workflows/read-configuration.yml
    with:
      path: ./.github/configurations/vllm-tensorizer.yml
  build:
    uses: ./.github/workflows/build.yml
    needs: get-config
    strategy:
      matrix: ${{ fromJSON(needs.get-config.outputs.config) }}
    secrets: inherit
    with:
      image-name: vllm-tensorizer
      folder: vllm-tensorizer
      tag-suffix: ${{ matrix.vllm-commit }}
      build-args: |
        VLLM_COMMIT=${{ matrix.vllm-commit }}
        FLASHINFER_COMMIT=${{ matrix.flashinfer-commit }}
        BASE_IMAGE=${{ matrix.builder-base-image }}
        LEAN_BASE_IMAGE=${{ matrix.final-base-image }}
